export const projectsData = [
  {
    id: 'prj1',
    category: 'app',
    title: 'Project title 1',
    date: 2018,
    industry: 'Finance',
    client: 'Creative Agency',
    timeline: '6 months',
    website: {
      name: 'example1.com',
      link: 'https://example1.com/',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
  {
    id: 'prj2',
    category: 'website',
    title: 'Project title 2',
    date: 2019,
    industry: 'Sport',
    client: 'Sports Company',
    timeline: '3 months',
    website: {
      name: 'example2.com',
      link: 'https://example2.com/',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
  {
    id: 'prj3',
    category: 'website',
    title: 'Project title 3',
    date: 2021,
    industry: 'Travel',
    client: 'Travel Agency',
    timeline: '4 months',
    website: {
      name: 'example3.com',
      link: 'https://example3.com/',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
  {
    id: 'prj4',
    category: 'website',
    title: 'Project title 4',
    date: 2020,
    industry: 'Live Media',
    client: 'Media Company',
    timeline: '5 months',
    website: {
      name: 'example4.com',
      link: 'https://example4.com/',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
  {
    id: 'prj5',
    category: 'interaction',
    title: 'Project title 5',
    date: 2023,
    industry: 'Automotive',
    client: 'Automotive Tech',
    timeline: '8 months',
    website: {
      name: 'example5.com',
      link: 'https://example5.com/',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
  {
    id: 'prj6',
    category: 'app',
    title: 'Project title 6',
    date: 2024,
    industry: 'Live Media',
    client: 'Media Production',
    timeline: '7 months',
    website: {
      name: 'example6.com',
      link: 'https://example6.com/',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
  {
    id: 'prj7',
    category: 'website',
    title: 'Project title 7',
    date: 2023,
    industry: 'Tourism',
    client: 'Tourism Board',
    timeline: '5 months',
    website: {
      name: 'example7.com',
      link: 'https://example7.com/',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
  {
    id: 'prj8',
    category: 'app',
    title: 'Project title 8',
    date: 2024,
    industry: 'Ecommerce',
    client: 'Ecommerce Store',
    timeline: '6 months',
    website: {
      name: 'example8.com',
      link: 'https://example8.com/',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
  {
    id: 'prj9',
    category: 'interaction',
    title: 'Project title 9',
    date: 2024,
    industry: 'Healthcare',
    client: 'Health Tech',
    timeline: '9 months',
    website: {
      name: 'example9.com',
      link: 'https://example9.com/',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
  {
    id: 'prj10',
    category: 'app',
    title: 'Project title 10',
    date: 2024,
    industry: 'Security System',
    client: 'Security Solutions',
    timeline: '10 months',
    website: {
      name: 'example10.com',
      link: 'https://example10.com/',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
  {
    id: 'prj11',
    category: 'website',
    title: 'Project title 11',
    date: 2024,
    industry: 'Healthcare',
    client: 'Healthcare Solutions',
    timeline: '8 months',
    website: {
      name: 'example11.com',
      link: 'https://example11.com/',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
  {
    id: 'prj12',
    category: 'website',
    title: 'Project title 12',
    date: 2024,
    industry: 'Ecommerce',
    client: 'Online Retail',
    timeline: '6 months',
    website: {
      name: 'example12.com',
      link: 'https://example12.com/',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
  {
    id: 'prj13',
    category: 'interaction',
    title: 'Project title 13',
    date: 2023,
    industry: 'Ecommerce',
    client: 'Ecommerce Solutions',
    timeline: '7 months',
    website: {
      name: 'example13.com',
      link: 'https://example13.com/',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
  {
    id: 'prj14',
    category: 'website',
    title: 'Project title 14',
    date: 2020,
    industry: 'Live Media',
    client: 'Media Streaming',
    timeline: '4 months',
    website: {
      name: 'example14.com',
      link: 'https://example14.com/',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
  {
    id: 'prj15',
    category: 'interaction',
    title: 'Project title 15',
    date: 2021,
    industry: 'Tourism',
    client: 'Tourism App',
    timeline: '5 months',
    website: {
      name: 'example15.com',
      link: 'https://example15.com',
    },
    descr: [
      'Duis aute irure dolor in reprehenderit in voluptate velit esse   cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut  enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    ],
    images: [
      'project-img-1.jpg',
      'project-img-2.jpg',
      'project-img-3.jpg',
      'project-img-4.jpg',
    ],
  },
];

export const reviewsData = [
  {
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pellentesque eu enim eget luctus. Sed augue felis, facilisis et elementum vitae, aliquam sit amet ante. Sed iaculis eros sem, elementum consequat est consequat eu. Quisque aliquet a ipsum nec tincidunt. Nulla vitae rhoncus leo. Praesent dui sapien, bibendum quis tempus dictum.',
    author: 'Edward M. Brooks',
    company: 'Marketing House',
    rating: 4,
  },
  {
    text: 'Vestibulum auctor mi sit amet mauris ultrices, vel tincidunt purus vulputate. Duis vitae leo a justo condimentum imperdiet vel in sapien. In hac habitasse platea dictumst. Nulla facilisi. Aliquam erat volutpat.',
    author: 'Alice R. Johnson',
    company: 'Tech Innovations',
    rating: 3,
  },
  {
    text: 'Suspendisse potenti. Cras eget nisi vel elit scelerisque posuere. Curabitur sit amet augue non nunc viverra scelerisque. Integer ullamcorper cursus lacus vel consequat. Sed eu orci auctor, malesuada odio ut, malesuada libero.',
    author: 'David K. Anderson',
    company: 'Data Systems Inc.',
    rating: 5,
  },
  {
    text: 'Phasellus vel quam vel est accumsan cursus. In hac habitasse platea dictumst. Suspendisse ut justo a urna facilisis scelerisque nec non neque. Nulla facilisi. Sed tincidunt risus nec purus euismod, at volutpat odio vulputate.',
    author: 'Emily L. Rodriguez',
    company: 'Digital Dynamics',
    rating: 3,
  },
  {
    text: 'Quisque at velit ut justo imperdiet varius in eu orci. Nulla facilisi. Sed fringilla nunc eu arcu facilisis, vitae placerat nisl efficitur. Sed vel sapien quis justo ullamcorper vehicula. Morbi euismod dapibus justo, nec fermentum justo mattis ut.',
    author: 'George W. Thompson',
    company: 'Innovate Tech',
    rating: 4,
  },
  {
    text: 'Integer vel urna eu ex feugiat euismod. Fusce vestibulum risus vel metus laoreet, vel eleifend purus suscipit. Maecenas aliquam metus eu metus luctus, in interdum justo auctor. Sed vel leo nec arcu vestibulum luctus nec eu ante.',
    author: 'Olivia P. Lewis',
    company: 'Tech Trends',
    rating: 5,
  },
  {
    text: 'Cras in tortor vel quam dictum pharetra. Ut sit amet purus non mauris cursus dapibus. Sed a orci vitae enim fermentum fermentum. Vestibulum vel sapien vel arcu elementum tincidunt. Vivamus tincidunt est eget odio ultricies, eu convallis felis dictum.',
    author: 'Michael E. Turner',
    company: 'Digital Solutions Co.',
    rating: 3,
  },
  {
    text: 'Duis id enim id elit malesuada suscipit eu eu lacus. Aenean at nisl vel mi dictum efficitur. Vestibulum a ligula vel sapien consectetur facilisis. Nam lacinia justo sit amet venenatis sodales. Etiam sed elit quis dolor tristique sodales.',
    author: 'Sophia J. White',
    company: 'InnoTech Innovations',
    rating: 3,
  },
  {
    text: 'Aliquam vel metus vel tellus scelerisque euismod a ac arcu. Duis tincidunt velit non nibh fermentum, vel bibendum nulla tristique. Integer cursus, odio a commodo tempus, quam dui bibendum purus, sit amet lacinia elit ex eu elit.',
    author: 'William M. Taylor',
    company: 'Data Innovations',
    rating: 4,
  },
  {
    text: 'Maecenas sit amet augue id urna feugiat iaculis vitae at erat. Sed luctus leo at congue pharetra. Proin nec felis tincidunt, placerat velit vel, auctor nisl. Nam nec est vitae justo accumsan hendrerit sit amet in lacus.',
    author: 'Emma R. Harris',
    company: 'Tech Solutions Plus',
    rating: 5,
  },
];

export const articlesData = [
  {
    category: 'category',
    title: 'TEN THE BEST APP IN 2017',
    date: '10/06/2023',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pellentesque eu enim eget luctus. Sed augue felis, facilisis et elementum vitae, aliquam sit amet ante. Sed iaculis eros sem, elementum consequat.',
  },
  {
    category: 'category',
    title: 'WEBSITE INSPIRATION',
    date: '15/08/2023',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pellentesque eu enim eget luctus. Sed augue felis, facilisis et elementum vitae, aliquam sit amet ante. Sed iaculis eros sem, elementum consequat.',
  },
  {
    category: 'category',
    title: 'CHANGES IN SOCIAL MEDIA',
    date: '20/10/2023',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pellentesque eu enim eget luctus. Sed augue felis, facilisis et elementum vitae, aliquam sit amet ante. Sed iaculis eros sem, elementum consequat.',
  },
  {
    category: 'category',
    title: 'Title 1',
    date: '12/12/2023',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pellentesque eu enim eget luctus. Sed augue felis, facilisis et elementum vitae, aliquam sit amet ante. Sed iaculis eros sem, elementum consequat.',
  },
  {
    category: 'category',
    title: 'Title 2',
    date: '01/01/2024',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pellentesque eu enim eget luctus. Sed augue felis, facilisis et elementum vitae, aliquam sit amet ante. Sed iaculis eros sem, elementum consequat.',
  },
  {
    category: 'category',
    title: 'Title 3',
    date: '08/11/2022',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pellentesque eu enim eget luctus. Sed augue felis, facilisis et elementum vitae, aliquam sit amet ante. Sed iaculis eros sem, elementum consequat.',
  },
  {
    category: 'category',
    title: 'Title 4',
    date: '07/08/2023',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pellentesque eu enim eget luctus. Sed augue felis, facilisis et elementum vitae, aliquam sit amet ante. Sed iaculis eros sem, elementum consequat.',
  },
  {
    category: 'category',
    title: 'Title 5',
    date: '11/04/2023',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pellentesque eu enim eget luctus. Sed augue felis, facilisis et elementum vitae, aliquam sit amet ante. Sed iaculis eros sem, elementum consequat.',
  },
  {
    category: 'category',
    title: 'Title 6',
    date: '01/09/2023',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pellentesque eu enim eget luctus. Sed augue felis, facilisis et elementum vitae, aliquam sit amet ante. Sed iaculis eros sem, elementum consequat.',
  },
  {
    category: 'category',
    title: 'Title 7',
    date: '08/02/2021',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pellentesque eu enim eget luctus. Sed augue felis, facilisis et elementum vitae, aliquam sit amet ante. Sed iaculis eros sem, elementum consequat.',
  },
];
